# Generated by Django 5.0.4 on 2024-05-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
