# Generated by Django 5.0.4 on 2024-05-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
