# Generated by Django 5.0.4 on 2024-05-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_admin',
            field=models.ImageField(default='profile_images/default_admin.png', upload_to='profile_images/'),
        ),
    ]
