# Generated by Django 5.0.4 on 2024-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_options_ticket_category_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature Request', 'Cerere Funcționalitate'), ('Customer Support', 'Suport Client'), ('Sales', 'Vânzări'), ('Feedback', 'Feedback'), ('Other', 'Altele')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Very Low', 'Foarte Scăzut'), ('Low', 'Scăzut'), ('Medium', 'Mediu'), ('High', 'Ridicat'), ('Very High', 'Foarte Ridicat')], default='Low', max_length=9),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Active', 'Activ'), ('Completed', 'Completat'), ('Pending', 'În așteptare')], max_length=20),
        ),
    ]
