# Generated by Django 5.0.4 on 2024-05-28 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_remove_ticket_ticket_number_alter_ticket_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Active', 'Activ'), ('Completed', 'Completat'), ('Pending', 'În așteptare')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='ticket_tick_priorit_58f4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category'], name='ticket_tick_categor_74ae16_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_status'], name='ticket_tick_ticket__19f22a_idx'),
        ),
    ]
