# Generated by Django 5.0.4 on 2024-05-28 15:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_options_ticket_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date_created'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('title', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['date_created'], name='ticket_tick_date_cr_667221_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['updated_at'], name='ticket_tick_updated_058a9b_idx'),
        ),
    ]
